# Created with YamlCreate.ps1 v2.2.10 $debug=QUSU.CRLF.5-1-22621-1778.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: InfamousJoeG.cybr-cli
PackageVersion: 1.0.1
InstallerLocale: en-US
InstallerType: zip
FileExtensions:
- json
- yaml
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cybr.exe
    PortableCommandAlias: cybr
  InstallerUrl: https://github.com/infamousjoeg/cybr-cli/releases/download/v1.0.1-release/cybr-cli_1.0.1-release_windows_amd64.zip
  InstallerSha256: 379868b2bb0adcfe1cb637079e95ff5179f378eff71737dbd5c345e87acbe201
- Architecture: arm64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cybr.exe
    PortableCommandAlias: cybr
  InstallerUrl: https://github.com/infamousjoeg/cybr-cli/releases/download/v1.0.1-release/cybr-cli_1.0.1-release_windows_arm64.zip
  InstallerSha256: 9d992d807f71c5ffc62b5ac6e149701f75f2230512213a6fd2ab3a2997427289
ManifestType: installer
ManifestVersion: 1.5.0
